### ISSUE TITLE
Should Not Throw On SimplePath Expressions

### ISSUE THREAD

**Issue by chadhietala** [tildeio/glimmer#414]
I started doing the work to get glimmer master and ember master to work again but ran across some issues. It appears that #402 deleted the tests around this that are [mirroring the ones on the Ember side](https://github.com/emberjs/ember.js/blob/79d90b9d95adade574654c19f1ba4e7124ad35e3/packages/ember-glimmer/tests/integration/components/contextual-components-test.js#L257).

This is going to be a semver 🚓  breaking change 🚓 if we require closed over components to be statically hinted that they evaluate to components.

/cc @chancancode

**Comment by rwjblue** [comment]
I believe the idea was that the Ember updates would require an AST transform for this?

Need @chancancode to chime in though...

**Comment by chadhietala** [comment]
I believe that is quite difficult to do without MU.

**Comment by chancancode** [comment]
> I believe the idea was that the Ember updates would require an AST transform for this?

confirm

> I believe that is quite difficult to do without MU.

d, it's just a static transformation – when you see `{{foo.bar with some=args}}` (which is now an invalid syntax in Glimmer), always transform it into `{{component foo.bar with some=args}}` because that is the only thing it could mean (regular component names cannot have dots, helpers cannot name have dots and cannot be dynamically yielded like that)

**Comment by rwjblue** [comment]
@chancancode What about `{{foo.bar.without.arguments.or.hash}}`?

**Comment by chancancode** [comment]
that would be the "content deopt" (which I think still works on master)

**Comment by chancancode** [comment]
@wycats says:

Just to be clear, `{{foo.bar}}` and `{{foo.bar baz}}` are both supported in the semantics. In terms of implementation, `{{foo.bar baz}}` is "easier" for now because we know ahead of time that it can only be a component. `{{foo.bar}}` is harder because we can't know until runtime what's going on.

For now, the easiest implementation strategy is to ahead-of-time transform the cases we know statically (`{{foo.bar baz}})`, and dynamically triage the cases that are ambiguous (`{{foo.bar}}`). Eventually, we will want to do an implementation-side unification ("appendable"), but we don't need to do that yet and shouldn't slow down the stack branch to do that unification.
